services:
  php56:
    image: php:5.6.40
  php74:
    image: php:7.4.33
  php80:
    image: php:8.0.30
  php81:
    image: php:8.1.31
  php82:
    image: php:8.2.26
  php83:
    image: php:8.3.14
  php84:
    image: php:8.4.3
