name: Continuous Integration
on: [push]
jobs:
  tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-20.04]
    steps:
      - name: cdout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache npm packages
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install npm dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: make node_modules
      - name: linter markdown
        run: make linter readme
      - name: linter docker
        run: make linter dockerfile
  nodejs:
      needs: tests
      runs-on: ubuntu-20.04
      steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
              submodules: recursive
          - name: 'Generate image'
            run: make docker-generate nodejs
  django:
      needs: tests
      runs-on: ubuntu-20.04
      steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
              submodules: recursive
          - name: 'Generate image'
            run: make docker-generate django
  phpfpm:
      needs: tests
      runs-on: ubuntu-20.04
      steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
              submodules: recursive
          - name: 'Generate image'
            run: make docker-generate phpfpm