name: Continuous Integration
on: [push]
jobs:
  tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache npm packages
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install npm dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: make node_modules
      - name: linter markdown
        run: make linter readme
      - name: linter docker
        run: make linter docker
  nodejs:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: 'Generate image'
            run: make docker generate-nodejs
  django:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: 'Generate image'
            run: make docker generate-django
  phpfpm:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: 'Generate image'
            run: make docker generate-phpfpm