name: ci
on: [push]
jobs:
  start:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-20.04]
    steps:
      - name: cdout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install npm dependencies
        run: npm install
      - name: linter markdown
        run: npm run lint:markdown
      - name: linter docker
        continue-on-error: true
        run: npm run lint:docker
  generate-jobs:
    name: Generate Jobs
    runs-on: ubuntu-latest
    outputs:
      strategy: ${{ steps.generate-jobs.outputs.strategy }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker-library/bashbrew@HEAD
      - id: generate-jobs
        name: Generate Jobs
        run: jq .php matrix.json >> "$GITHUB_OUTPUT"
  php:
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-jobs.outputs.strategy) }}
    name: PHP ${{ matrix.version }}
    needs: start
    runs-on: ubuntu-20.04
    steps:
      - name: cdout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install npm dependencies
        run: npm install
      - name: "Generate file SH"
        if: matrix.latest == 'off'
        run: npm run docker:build:php --folder=${{ matrix.version }}
      - name: "Generate file SH IF LAST"
        if: matrix.latest == 'on'
        run: npm run docker:build:php --folder=${{ matrix.version }} --latest
      - name: "Build image"
        run: ./build-php-${{ matrix.version }}.sh
      - name: "Show images"
        run: npm run docker:image:ls
      - name: Set up QEMU
        if: github.ref == 'refs/heads/main'
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        if: github.ref == 'refs/heads/main'
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker
        if: github.ref == 'refs/heads/main'
        run: npm run docker:push:php

