name: Continuous Integration
on: [push]
jobs:
  start:
    runs-on: ubuntu-20.04
    steps:
      - name: cdout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache npm packages
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install npm dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: make node_modules
  tests:
    needs: start
    runs-on: ubuntu-20.04
    steps:
      - name: cdout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache npm packages
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: linter markdown
        run: make linter readme
      - name: linter docker
        run: make linter dockerfile
  django:
      strategy:
        matrix:
          django: [2.2.27, 3.2.12, 4.0.2]
      name: DJANGO ${{ matrix.django }}
      needs: tests
      runs-on: ubuntu-20.04
      steps:
      - name: cdout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: 'Generate image'
        run: make generate-django ${{ matrix.django }}
      - name: 'Set latest'
        if: matrix.django == '4.0.2'
        run: make latest-django ${{ matrix.django }}
      - name: Set up QEMU
        if: github.ref == 'refs/heads/main'
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        if: github.ref == 'refs/heads/main'
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker
        if: github.ref == 'refs/heads/main'
        run: make push django
  phpfpm:
      strategy:
        matrix:
          php: [5.6.40, 7.4.27, 8.0.15, 8.1.2]
      name: PHP ${{ matrix.php }}
      needs: tests
      runs-on: ubuntu-20.04
      steps:
      - name: cdout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: 'Generate image'
        run: make generate-phpfpm ${{ matrix.php }}
      - name: 'Set latest'
        if: matrix.php == '8.1.2'
        run: make latest-phpfpm ${{ matrix.php }}
      - name: Set up QEMU
        if: github.ref == 'refs/heads/main'
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        if: github.ref == 'refs/heads/main'
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker
        if: github.ref == 'refs/heads/main'
        run: make push phpfpm
  angular:
      strategy:
        matrix:
          angular: [10.2.4, 11.2.18, 12.2.16, 13.2.2]
      name: ANGULAR ${{ matrix.angular }}
      needs: tests
      runs-on: ubuntu-20.04
      steps:
      - name: cdout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: 'Generate image'
        run: make generate-angular ${{ matrix.angular }}
      - name: 'Set latest'
        if: matrix.angular == '13.2.2'
        run: make latest-angular ${{ matrix.angular }}
      - name: Set up QEMU
        if: github.ref == 'refs/heads/main'
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        if: github.ref == 'refs/heads/main'
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker
        if: github.ref == 'refs/heads/main'
        run: make push angular
  quasar:
      strategy:
        matrix:
          quasar: [1.1.3, 1.2.2]
      name: QUASAR ${{ matrix.quasar }}
      needs: tests
      runs-on: ubuntu-20.04
      steps:
      - name: cdout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: 'Generate image'
        run: make generate-quasar ${{ matrix.quasar }}
      - name: 'Set latest'
        if: matrix.quasar == '1.2.2'
        run: make latest-quasar ${{ matrix.quasar }}
      - name: Set up QEMU
        if: github.ref == 'refs/heads/main'
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        if: github.ref == 'refs/heads/main'
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker
        if: github.ref == 'refs/heads/main'
        run: make push quasar
  nodejs:
      strategy:
        matrix:
          nodejs: [4.9.1, 5.12.0, 6.17.1, 7.10.1, 8.17.0, 9.11.2, 10.24.1, 11.15.0, 12.22.10, 13.14.0, 14.19.0, 15.14.0, 16.13.2, 17.4.0]
      name: NODEJS ${{ matrix.nodejs }}
      needs: tests
      runs-on: ubuntu-20.04
      steps:
      - name: cdout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: 'Generate image'
        run: make generate-nodejs ${{ matrix.nodejs }}
      - name: 'Set latest'
        if: matrix.nodejs == '17.4.0'
        run: make latest-nodejs ${{ matrix.nodejs }}
      - name: Set up QEMU
        if: github.ref == 'refs/heads/main'
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        if: github.ref == 'refs/heads/main'
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker
        if: github.ref == 'refs/heads/main'
        run: make push nodejs